INSERT INTO scylla_talk_ks.user (id,name,email,about) VALUES (uuid(),'a name','some@email.net','about me');
INSERT INTO scylla_talk_ks.user (id,name,email,about) VALUES (uuid(),'a name','some@email.net','about me');
INSERT INTO scylla_talk_ks.user (id,name,email,about) VALUES (uuid(),'a name','some@email.net','about me');
INSERT INTO scylla_talk_ks.user (id,name,email,about) VALUES (uuid(),'a name','some@email.net','about me');
INSERT INTO scylla_talk_ks.user (id,name,email,about) VALUES (uuid(),'a name','some@email.net','about me');